USE k_car_navigator;

-- region insert
INSERT IGNORE INTO region (code, name) VALUES ('01', '서울');
INSERT IGNORE INTO region (code, name) VALUES ('02', '부산');
INSERT IGNORE INTO region (code, name) VALUES ('03', '대구');
INSERT IGNORE INTO region (code, name) VALUES ('04', '인천');
INSERT IGNORE INTO region (code, name) VALUES ('05', '광주');
INSERT IGNORE INTO region (code, name) VALUES ('06', '대전');
INSERT IGNORE INTO region (code, name) VALUES ('07', '울산');
INSERT IGNORE INTO region (code, name) VALUES ('08', '세종');
INSERT IGNORE INTO region (code, name) VALUES ('09', '경기');
INSERT IGNORE INTO region (code, name) VALUES ('10', '강원');
INSERT IGNORE INTO region (code, name) VALUES ('11', '충북');
INSERT IGNORE INTO region (code, name) VALUES ('12', '충남');
INSERT IGNORE INTO region (code, name) VALUES ('13', '전북');
INSERT IGNORE INTO region (code, name) VALUES ('14', '전남');
INSERT IGNORE INTO region (code, name) VALUES ('15', '경북');
INSERT IGNORE INTO region (code, name) VALUES ('16', '경남');
INSERT IGNORE INTO region (code, name) VALUES ('17', '제주');

-- district insert
INSERT IGNORE INTO district (code, region_code, name) VALUES ('0101', '01', '강남');
INSERT IGNORE INTO district (code, region_code, name) VALUES ('0102', '01', '강동');
INSERT IGNORE INTO district (code, region_code, name) VALUES ('0103', '01', '강북');
INSERT IGNORE INTO district (code, region_code, name) VALUES ('0104', '01', '강서');
INSERT IGNORE INTO district (code, region_code, name) VALUES ('0105', '01', '관악');
INSERT IGNORE INTO district (code, region_code, name) VALUES ('0106', '01', '광진');
INSERT IGNORE INTO district (code, region_code, name) VALUES ('0107', '01', '구로');
INSERT IGNORE INTO district (code, region_code, name) VALUES ('0108', '01', '금천');
INSERT IGNORE INTO district (code, region_code, name) VALUES ('0109', '01', '노원');
INSERT IGNORE INTO district (code, region_code, name) VALUES ('0110', '01', '도봉');
INSERT IGNORE INTO district (code, region_code, name) VALUES ('0111', '01', '동대문');
INSERT IGNORE INTO district (code, region_code, name) VALUES ('0112', '01', '동작');
INSERT IGNORE INTO district (code, region_code, name) VALUES ('0113', '01', '마포');
INSERT IGNORE INTO district (code, region_code, name) VALUES ('0114', '01', '서대문');
INSERT IGNORE INTO district (code, region_code, name) VALUES ('0115', '01', '서초');
INSERT IGNORE INTO district (code, region_code, name) VALUES ('0116', '01', '성동');
INSERT IGNORE INTO district (code, region_code, name) VALUES ('0117', '01', '성북');
INSERT IGNORE INTO district (code, region_code, name) VALUES ('0118', '01', '송파');
INSERT IGNORE INTO district (code, region_code, name) VALUES ('0119', '01', '양천');
INSERT IGNORE INTO district (code, region_code, name) VALUES ('0120', '01', '영등포');
INSERT IGNORE INTO district (code, region_code, name) VALUES ('0121', '01', '용산');
INSERT IGNORE INTO district (code, region_code, name) VALUES ('0122', '01', '은평');
INSERT IGNORE INTO district (code, region_code, name) VALUES ('0123', '01', '종로');
INSERT IGNORE INTO district (code, region_code, name) VALUES ('0124', '01', '중');
INSERT IGNORE INTO district (code, region_code, name) VALUES ('0125', '01', '중랑');
INSERT IGNORE INTO district (code, region_code, name) VALUES ('0201', '02', '강서');
INSERT IGNORE INTO district (code, region_code, name) VALUES ('0202', '02', '금정');
INSERT IGNORE INTO district (code, region_code, name) VALUES ('0203', '02', '기장');
INSERT IGNORE INTO district (code, region_code, name) VALUES ('0204', '02', '남');
INSERT IGNORE INTO district (code, region_code, name) VALUES ('0205', '02', '동');
INSERT IGNORE INTO district (code, region_code, name) VALUES ('0206', '02', '동래');
INSERT IGNORE INTO district (code, region_code, name) VALUES ('0207', '02', '부산진');
INSERT IGNORE INTO district (code, region_code, name) VALUES ('0208', '02', '북');
INSERT IGNORE INTO district (code, region_code, name) VALUES ('0209', '02', '사상');
INSERT IGNORE INTO district (code, region_code, name) VALUES ('0210', '02', '사하');
INSERT IGNORE INTO district (code, region_code, name) VALUES ('0211', '02', '서');
INSERT IGNORE INTO district (code, region_code, name) VALUES ('0212', '02', '수영');
INSERT IGNORE INTO district (code, region_code, name) VALUES ('0213', '02', '연제');
INSERT IGNORE INTO district (code, region_code, name) VALUES ('0214', '02', '영도');
INSERT IGNORE INTO district (code, region_code, name) VALUES ('0215', '02', '중');
INSERT IGNORE INTO district (code, region_code, name) VALUES ('0216', '02', '해운대');
INSERT IGNORE INTO district (code, region_code, name) VALUES ('0301', '03', '남');
INSERT IGNORE INTO district (code, region_code, name) VALUES ('0302', '03', '달서');
INSERT IGNORE INTO district (code, region_code, name) VALUES ('0303', '03', '달성');
INSERT IGNORE INTO district (code, region_code, name) VALUES ('0304', '03', '동');
INSERT IGNORE INTO district (code, region_code, name) VALUES ('0305', '03', '북');
INSERT IGNORE INTO district (code, region_code, name) VALUES ('0306', '03', '서');
INSERT IGNORE INTO district (code, region_code, name) VALUES ('0307', '03', '수성');
INSERT IGNORE INTO district (code, region_code, name) VALUES ('0308', '03', '중');
INSERT IGNORE INTO district (code, region_code, name) VALUES ('0401', '04', '강화');
INSERT IGNORE INTO district (code, region_code, name) VALUES ('0402', '04', '계양');
INSERT IGNORE INTO district (code, region_code, name) VALUES ('0403', '04', '남동');
INSERT IGNORE INTO district (code, region_code, name) VALUES ('0404', '04', '동');
INSERT IGNORE INTO district (code, region_code, name) VALUES ('0405', '04', '미추홀');
INSERT IGNORE INTO district (code, region_code, name) VALUES ('0406', '04', '부평');
INSERT IGNORE INTO district (code, region_code, name) VALUES ('0407', '04', '서');
INSERT IGNORE INTO district (code, region_code, name) VALUES ('0408', '04', '연수');
INSERT IGNORE INTO district (code, region_code, name) VALUES ('0409', '04', '옹진');
INSERT IGNORE INTO district (code, region_code, name) VALUES ('0410', '04', '중');
INSERT IGNORE INTO district (code, region_code, name) VALUES ('0501', '05', '광산');
INSERT IGNORE INTO district (code, region_code, name) VALUES ('0502', '05', '남');
INSERT IGNORE INTO district (code, region_code, name) VALUES ('0503', '05', '동');
INSERT IGNORE INTO district (code, region_code, name) VALUES ('0504', '05', '북');
INSERT IGNORE INTO district (code, region_code, name) VALUES ('0505', '05', '서');
INSERT IGNORE INTO district (code, region_code, name) VALUES ('0601', '06', '대덕');
INSERT IGNORE INTO district (code, region_code, name) VALUES ('0602', '06', '동');
INSERT IGNORE INTO district (code, region_code, name) VALUES ('0603', '06', '서');
INSERT IGNORE INTO district (code, region_code, name) VALUES ('0604', '06', '유성');
INSERT IGNORE INTO district (code, region_code, name) VALUES ('0605', '06', '중');
INSERT IGNORE INTO district (code, region_code, name) VALUES ('0701', '07', '남');
INSERT IGNORE INTO district (code, region_code, name) VALUES ('0702', '07', '동');
INSERT IGNORE INTO district (code, region_code, name) VALUES ('0703', '07', '북');
INSERT IGNORE INTO district (code, region_code, name) VALUES ('0704', '07', '울주');
INSERT IGNORE INTO district (code, region_code, name) VALUES ('0705', '07', '중');
INSERT IGNORE INTO district (code, region_code, name) VALUES ('0801', '08', '세종특별자치');
INSERT IGNORE INTO district (code, region_code, name) VALUES ('0901', '09', '가평');
INSERT IGNORE INTO district (code, region_code, name) VALUES ('0902', '09', '고양 덕양');
INSERT IGNORE INTO district (code, region_code, name) VALUES ('0903', '09', '고양 일산동');
INSERT IGNORE INTO district (code, region_code, name) VALUES ('0904', '09', '고양 일산서');
INSERT IGNORE INTO district (code, region_code, name) VALUES ('0905', '09', '과천');
INSERT IGNORE INTO district (code, region_code, name) VALUES ('0906', '09', '광명');
INSERT IGNORE INTO district (code, region_code, name) VALUES ('0907', '09', '광주');
INSERT IGNORE INTO district (code, region_code, name) VALUES ('0908', '09', '구리');
INSERT IGNORE INTO district (code, region_code, name) VALUES ('0909', '09', '군포');
INSERT IGNORE INTO district (code, region_code, name) VALUES ('0910', '09', '김포');
INSERT IGNORE INTO district (code, region_code, name) VALUES ('0911', '09', '남양주');
INSERT IGNORE INTO district (code, region_code, name) VALUES ('0912', '09', '동두천');
INSERT IGNORE INTO district (code, region_code, name) VALUES ('0913', '09', '부천');
INSERT IGNORE INTO district (code, region_code, name) VALUES ('0914', '09', '성남 분당');
INSERT IGNORE INTO district (code, region_code, name) VALUES ('0915', '09', '성남 수정');
INSERT IGNORE INTO district (code, region_code, name) VALUES ('0916', '09', '성남 중원');
INSERT IGNORE INTO district (code, region_code, name) VALUES ('0917', '09', '수원 권선');
INSERT IGNORE INTO district (code, region_code, name) VALUES ('0918', '09', '수원 영통');
INSERT IGNORE INTO district (code, region_code, name) VALUES ('0919', '09', '수원 장안');
INSERT IGNORE INTO district (code, region_code, name) VALUES ('0920', '09', '수원 팔달');
INSERT IGNORE INTO district (code, region_code, name) VALUES ('0921', '09', '시흥');
INSERT IGNORE INTO district (code, region_code, name) VALUES ('0922', '09', '안산 단원');
INSERT IGNORE INTO district (code, region_code, name) VALUES ('0923', '09', '안산 상록');
INSERT IGNORE INTO district (code, region_code, name) VALUES ('0924', '09', '안성');
INSERT IGNORE INTO district (code, region_code, name) VALUES ('0925', '09', '안양 동안');
INSERT IGNORE INTO district (code, region_code, name) VALUES ('0926', '09', '안양 만안');
INSERT IGNORE INTO district (code, region_code, name) VALUES ('0927', '09', '양주');
INSERT IGNORE INTO district (code, region_code, name) VALUES ('0928', '09', '양평');
INSERT IGNORE INTO district (code, region_code, name) VALUES ('0929', '09', '여주');
INSERT IGNORE INTO district (code, region_code, name) VALUES ('0930', '09', '연천');
INSERT IGNORE INTO district (code, region_code, name) VALUES ('0931', '09', '오산');
INSERT IGNORE INTO district (code, region_code, name) VALUES ('0932', '09', '용인 기흥');
INSERT IGNORE INTO district (code, region_code, name) VALUES ('0933', '09', '용인 수지');
INSERT IGNORE INTO district (code, region_code, name) VALUES ('0934', '09', '용인 처인');
INSERT IGNORE INTO district (code, region_code, name) VALUES ('0935', '09', '의왕');
INSERT IGNORE INTO district (code, region_code, name) VALUES ('0936', '09', '의정부');
INSERT IGNORE INTO district (code, region_code, name) VALUES ('0937', '09', '이천');
INSERT IGNORE INTO district (code, region_code, name) VALUES ('0938', '09', '파주');
INSERT IGNORE INTO district (code, region_code, name) VALUES ('0939', '09', '평택');
INSERT IGNORE INTO district (code, region_code, name) VALUES ('0940', '09', '포천');
INSERT IGNORE INTO district (code, region_code, name) VALUES ('0941', '09', '하남');
INSERT IGNORE INTO district (code, region_code, name) VALUES ('0942', '09', '화성');
INSERT IGNORE INTO district (code, region_code, name) VALUES ('1001', '10', '강릉');
INSERT IGNORE INTO district (code, region_code, name) VALUES ('1002', '10', '고성');
INSERT IGNORE INTO district (code, region_code, name) VALUES ('1003', '10', '동해');
INSERT IGNORE INTO district (code, region_code, name) VALUES ('1004', '10', '삼척');
INSERT IGNORE INTO district (code, region_code, name) VALUES ('1005', '10', '속초');
INSERT IGNORE INTO district (code, region_code, name) VALUES ('1006', '10', '양구');
INSERT IGNORE INTO district (code, region_code, name) VALUES ('1007', '10', '양양');
INSERT IGNORE INTO district (code, region_code, name) VALUES ('1008', '10', '영월');
INSERT IGNORE INTO district (code, region_code, name) VALUES ('1009', '10', '원주');
INSERT IGNORE INTO district (code, region_code, name) VALUES ('1010', '10', '인제');
INSERT IGNORE INTO district (code, region_code, name) VALUES ('1011', '10', '정선');
INSERT IGNORE INTO district (code, region_code, name) VALUES ('1012', '10', '철원');
INSERT IGNORE INTO district (code, region_code, name) VALUES ('1013', '10', '춘천');
INSERT IGNORE INTO district (code, region_code, name) VALUES ('1014', '10', '태백');
INSERT IGNORE INTO district (code, region_code, name) VALUES ('1015', '10', '평창');
INSERT IGNORE INTO district (code, region_code, name) VALUES ('1016', '10', '홍천');
INSERT IGNORE INTO district (code, region_code, name) VALUES ('1017', '10', '화천');
INSERT IGNORE INTO district (code, region_code, name) VALUES ('1018', '10', '횡성');
INSERT IGNORE INTO district (code, region_code, name) VALUES ('1101', '11', '괴산');
INSERT IGNORE INTO district (code, region_code, name) VALUES ('1102', '11', '단양');
INSERT IGNORE INTO district (code, region_code, name) VALUES ('1103', '11', '보은');
INSERT IGNORE INTO district (code, region_code, name) VALUES ('1104', '11', '영동');
INSERT IGNORE INTO district (code, region_code, name) VALUES ('1105', '11', '옥천');
INSERT IGNORE INTO district (code, region_code, name) VALUES ('1106', '11', '음성');
INSERT IGNORE INTO district (code, region_code, name) VALUES ('1107', '11', '제천');
INSERT IGNORE INTO district (code, region_code, name) VALUES ('1108', '11', '증평');
INSERT IGNORE INTO district (code, region_code, name) VALUES ('1109', '11', '진천');
INSERT IGNORE INTO district (code, region_code, name) VALUES ('1110', '11', '청원');
INSERT IGNORE INTO district (code, region_code, name) VALUES ('1111', '11', '청주 상당');
INSERT IGNORE INTO district (code, region_code, name) VALUES ('1112', '11', '청주 서원');
INSERT IGNORE INTO district (code, region_code, name) VALUES ('1113', '11', '청주 청원');
INSERT IGNORE INTO district (code, region_code, name) VALUES ('1114', '11', '청주 흥덕');
INSERT IGNORE INTO district (code, region_code, name) VALUES ('1115', '11', '충주');
INSERT IGNORE INTO district (code, region_code, name) VALUES ('1201', '12', '계룡');
INSERT IGNORE INTO district (code, region_code, name) VALUES ('1202', '12', '공주');
INSERT IGNORE INTO district (code, region_code, name) VALUES ('1203', '12', '금산');
INSERT IGNORE INTO district (code, region_code, name) VALUES ('1204', '12', '논산');
INSERT IGNORE INTO district (code, region_code, name) VALUES ('1205', '12', '당진');
INSERT IGNORE INTO district (code, region_code, name) VALUES ('1206', '12', '보령');
INSERT IGNORE INTO district (code, region_code, name) VALUES ('1207', '12', '부여');
INSERT IGNORE INTO district (code, region_code, name) VALUES ('1208', '12', '서산');
INSERT IGNORE INTO district (code, region_code, name) VALUES ('1209', '12', '서천');
INSERT IGNORE INTO district (code, region_code, name) VALUES ('1210', '12', '아산');
INSERT IGNORE INTO district (code, region_code, name) VALUES ('1211', '12', '예산');
INSERT IGNORE INTO district (code, region_code, name) VALUES ('1212', '12', '천안 동남');
INSERT IGNORE INTO district (code, region_code, name) VALUES ('1213', '12', '천안 서북');
INSERT IGNORE INTO district (code, region_code, name) VALUES ('1214', '12', '청양');
INSERT IGNORE INTO district (code, region_code, name) VALUES ('1215', '12', '태안');
INSERT IGNORE INTO district (code, region_code, name) VALUES ('1216', '12', '홍성');
INSERT IGNORE INTO district (code, region_code, name) VALUES ('1301', '13', '고창');
INSERT IGNORE INTO district (code, region_code, name) VALUES ('1302', '13', '군산');
INSERT IGNORE INTO district (code, region_code, name) VALUES ('1303', '13', '김제');
INSERT IGNORE INTO district (code, region_code, name) VALUES ('1304', '13', '남원');
INSERT IGNORE INTO district (code, region_code, name) VALUES ('1305', '13', '무주');
INSERT IGNORE INTO district (code, region_code, name) VALUES ('1306', '13', '부안');
INSERT IGNORE INTO district (code, region_code, name) VALUES ('1307', '13', '순창');
INSERT IGNORE INTO district (code, region_code, name) VALUES ('1308', '13', '완주');
INSERT IGNORE INTO district (code, region_code, name) VALUES ('1309', '13', '익산');
INSERT IGNORE INTO district (code, region_code, name) VALUES ('1310', '13', '임실');
INSERT IGNORE INTO district (code, region_code, name) VALUES ('1311', '13', '장수');
INSERT IGNORE INTO district (code, region_code, name) VALUES ('1312', '13', '전주 덕진');
INSERT IGNORE INTO district (code, region_code, name) VALUES ('1313', '13', '전주 완산');
INSERT IGNORE INTO district (code, region_code, name) VALUES ('1314', '13', '정읍');
INSERT IGNORE INTO district (code, region_code, name) VALUES ('1315', '13', '진안');
INSERT IGNORE INTO district (code, region_code, name) VALUES ('1401', '14', '강진');
INSERT IGNORE INTO district (code, region_code, name) VALUES ('1402', '14', '고흥');
INSERT IGNORE INTO district (code, region_code, name) VALUES ('1403', '14', '곡성');
INSERT IGNORE INTO district (code, region_code, name) VALUES ('1404', '14', '광양');
INSERT IGNORE INTO district (code, region_code, name) VALUES ('1405', '14', '구례');
INSERT IGNORE INTO district (code, region_code, name) VALUES ('1406', '14', '나주');
INSERT IGNORE INTO district (code, region_code, name) VALUES ('1407', '14', '담양');
INSERT IGNORE INTO district (code, region_code, name) VALUES ('1408', '14', '목포');
INSERT IGNORE INTO district (code, region_code, name) VALUES ('1409', '14', '무안');
INSERT IGNORE INTO district (code, region_code, name) VALUES ('1410', '14', '보성');
INSERT IGNORE INTO district (code, region_code, name) VALUES ('1411', '14', '순천');
INSERT IGNORE INTO district (code, region_code, name) VALUES ('1412', '14', '신안');
INSERT IGNORE INTO district (code, region_code, name) VALUES ('1413', '14', '여수');
INSERT IGNORE INTO district (code, region_code, name) VALUES ('1414', '14', '영광');
INSERT IGNORE INTO district (code, region_code, name) VALUES ('1415', '14', '영암');
INSERT IGNORE INTO district (code, region_code, name) VALUES ('1416', '14', '완도');
INSERT IGNORE INTO district (code, region_code, name) VALUES ('1417', '14', '장성');
INSERT IGNORE INTO district (code, region_code, name) VALUES ('1418', '14', '장흥');
INSERT IGNORE INTO district (code, region_code, name) VALUES ('1419', '14', '진도');
INSERT IGNORE INTO district (code, region_code, name) VALUES ('1420', '14', '함평');
INSERT IGNORE INTO district (code, region_code, name) VALUES ('1421', '14', '해남');
INSERT IGNORE INTO district (code, region_code, name) VALUES ('1422', '14', '화순');
INSERT IGNORE INTO district (code, region_code, name) VALUES ('1501', '15', '경산');
INSERT IGNORE INTO district (code, region_code, name) VALUES ('1502', '15', '경주');
INSERT IGNORE INTO district (code, region_code, name) VALUES ('1503', '15', '고령');
INSERT IGNORE INTO district (code, region_code, name) VALUES ('1504', '15', '구미');
INSERT IGNORE INTO district (code, region_code, name) VALUES ('1505', '15', '군위');
INSERT IGNORE INTO district (code, region_code, name) VALUES ('1506', '15', '김천');
INSERT IGNORE INTO district (code, region_code, name) VALUES ('1507', '15', '문경');
INSERT IGNORE INTO district (code, region_code, name) VALUES ('1508', '15', '봉화');
INSERT IGNORE INTO district (code, region_code, name) VALUES ('1509', '15', '상주');
INSERT IGNORE INTO district (code, region_code, name) VALUES ('1510', '15', '성주');
INSERT IGNORE INTO district (code, region_code, name) VALUES ('1511', '15', '안동');
INSERT IGNORE INTO district (code, region_code, name) VALUES ('1512', '15', '영덕');
INSERT IGNORE INTO district (code, region_code, name) VALUES ('1513', '15', '영양');
INSERT IGNORE INTO district (code, region_code, name) VALUES ('1514', '15', '영주');
INSERT IGNORE INTO district (code, region_code, name) VALUES ('1515', '15', '영천');
INSERT IGNORE INTO district (code, region_code, name) VALUES ('1516', '15', '예천');
INSERT IGNORE INTO district (code, region_code, name) VALUES ('1517', '15', '울릉');
INSERT IGNORE INTO district (code, region_code, name) VALUES ('1518', '15', '울진');
INSERT IGNORE INTO district (code, region_code, name) VALUES ('1519', '15', '의성');
INSERT IGNORE INTO district (code, region_code, name) VALUES ('1520', '15', '청도');
INSERT IGNORE INTO district (code, region_code, name) VALUES ('1521', '15', '청송');
INSERT IGNORE INTO district (code, region_code, name) VALUES ('1522', '15', '칠곡');
INSERT IGNORE INTO district (code, region_code, name) VALUES ('1523', '15', '포항 남');
INSERT IGNORE INTO district (code, region_code, name) VALUES ('1524', '15', '포항 북');
INSERT IGNORE INTO district (code, region_code, name) VALUES ('1601', '16', '거제');
INSERT IGNORE INTO district (code, region_code, name) VALUES ('1602', '16', '거창');
INSERT IGNORE INTO district (code, region_code, name) VALUES ('1603', '16', '고성');
INSERT IGNORE INTO district (code, region_code, name) VALUES ('1604', '16', '김해');
INSERT IGNORE INTO district (code, region_code, name) VALUES ('1605', '16', '남해');
INSERT IGNORE INTO district (code, region_code, name) VALUES ('1606', '16', '밀양');
INSERT IGNORE INTO district (code, region_code, name) VALUES ('1607', '16', '사천');
INSERT IGNORE INTO district (code, region_code, name) VALUES ('1608', '16', '산청');
INSERT IGNORE INTO district (code, region_code, name) VALUES ('1609', '16', '양산');
INSERT IGNORE INTO district (code, region_code, name) VALUES ('1610', '16', '의령');
INSERT IGNORE INTO district (code, region_code, name) VALUES ('1611', '16', '진주');
INSERT IGNORE INTO district (code, region_code, name) VALUES ('1612', '16', '창녕');
INSERT IGNORE INTO district (code, region_code, name) VALUES ('1613', '16', '창원 마산합포');
INSERT IGNORE INTO district (code, region_code, name) VALUES ('1614', '16', '창원 마산회원');
INSERT IGNORE INTO district (code, region_code, name) VALUES ('1615', '16', '창원 성산');
INSERT IGNORE INTO district (code, region_code, name) VALUES ('1616', '16', '창원 의창');
INSERT IGNORE INTO district (code, region_code, name) VALUES ('1617', '16', '창원 진해');
INSERT IGNORE INTO district (code, region_code, name) VALUES ('1618', '16', '통영');
INSERT IGNORE INTO district (code, region_code, name) VALUES ('1619', '16', '하동');
INSERT IGNORE INTO district (code, region_code, name) VALUES ('1620', '16', '함안');
INSERT IGNORE INTO district (code, region_code, name) VALUES ('1621', '16', '함양');
INSERT IGNORE INTO district (code, region_code, name) VALUES ('1622', '16', '합천');
INSERT IGNORE INTO district (code, region_code, name) VALUES ('1701', '17', '서귀포');
INSERT IGNORE INTO district (code, region_code, name) VALUES ('1702', '17', '제주');
INSERT IGNORE INTO district (code, region_code, name) VALUES ('0126', '01', '강남구');
INSERT IGNORE INTO district (code, region_code, name) VALUES ('0127', '01', '강동구');
INSERT IGNORE INTO district (code, region_code, name) VALUES ('0128', '01', '강북구');
INSERT IGNORE INTO district (code, region_code, name) VALUES ('0129', '01', '강서구');
INSERT IGNORE INTO district (code, region_code, name) VALUES ('0130', '01', '관악구');
INSERT IGNORE INTO district (code, region_code, name) VALUES ('0131', '01', '광진구');
INSERT IGNORE INTO district (code, region_code, name) VALUES ('0132', '01', '구로구');
INSERT IGNORE INTO district (code, region_code, name) VALUES ('0133', '01', '금천구');
INSERT IGNORE INTO district (code, region_code, name) VALUES ('0134', '01', '노원구');
INSERT IGNORE INTO district (code, region_code, name) VALUES ('0135', '01', '도봉구');
INSERT IGNORE INTO district (code, region_code, name) VALUES ('0136', '01', '동대문구');
INSERT IGNORE INTO district (code, region_code, name) VALUES ('0137', '01', '동작구');
INSERT IGNORE INTO district (code, region_code, name) VALUES ('0138', '01', '마포구');
INSERT IGNORE INTO district (code, region_code, name) VALUES ('0139', '01', '서대문구');
INSERT IGNORE INTO district (code, region_code, name) VALUES ('0140', '01', '서초구');
INSERT IGNORE INTO district (code, region_code, name) VALUES ('0141', '01', '성동구');
INSERT IGNORE INTO district (code, region_code, name) VALUES ('0142', '01', '성북구');
INSERT IGNORE INTO district (code, region_code, name) VALUES ('0143', '01', '송파구');
INSERT IGNORE INTO district (code, region_code, name) VALUES ('0144', '01', '양천구');
INSERT IGNORE INTO district (code, region_code, name) VALUES ('0145', '01', '영등포구');
INSERT IGNORE INTO district (code, region_code, name) VALUES ('0146', '01', '용산구');
INSERT IGNORE INTO district (code, region_code, name) VALUES ('0147', '01', '은평구');
INSERT IGNORE INTO district (code, region_code, name) VALUES ('0148', '01', '종로구');
INSERT IGNORE INTO district (code, region_code, name) VALUES ('0149', '01', '중구');
INSERT IGNORE INTO district (code, region_code, name) VALUES ('0150', '01', '중랑구');
INSERT IGNORE INTO district (code, region_code, name) VALUES ('0217', '02', '강서구');
INSERT IGNORE INTO district (code, region_code, name) VALUES ('0218', '02', '금정구');
INSERT IGNORE INTO district (code, region_code, name) VALUES ('0219', '02', '기장군');
INSERT IGNORE INTO district (code, region_code, name) VALUES ('0220', '02', '남구');
INSERT IGNORE INTO district (code, region_code, name) VALUES ('0221', '02', '동구');
INSERT IGNORE INTO district (code, region_code, name) VALUES ('0222', '02', '동래구');
INSERT IGNORE INTO district (code, region_code, name) VALUES ('0223', '02', '부산진구');
INSERT IGNORE INTO district (code, region_code, name) VALUES ('0224', '02', '북구');
INSERT IGNORE INTO district (code, region_code, name) VALUES ('0225', '02', '사상구');
INSERT IGNORE INTO district (code, region_code, name) VALUES ('0226', '02', '사하구');
INSERT IGNORE INTO district (code, region_code, name) VALUES ('0227', '02', '서구');
INSERT IGNORE INTO district (code, region_code, name) VALUES ('0228', '02', '수영구');
INSERT IGNORE INTO district (code, region_code, name) VALUES ('0229', '02', '연제구');
INSERT IGNORE INTO district (code, region_code, name) VALUES ('0230', '02', '영도구');
INSERT IGNORE INTO district (code, region_code, name) VALUES ('0231', '02', '중구');
INSERT IGNORE INTO district (code, region_code, name) VALUES ('0232', '02', '해운대구');
INSERT IGNORE INTO district (code, region_code, name) VALUES ('0309', '03', '군위군');
INSERT IGNORE INTO district (code, region_code, name) VALUES ('0310', '03', '남구');
INSERT IGNORE INTO district (code, region_code, name) VALUES ('0311', '03', '달서구');
INSERT IGNORE INTO district (code, region_code, name) VALUES ('0312', '03', '달성군');
INSERT IGNORE INTO district (code, region_code, name) VALUES ('0313', '03', '동구');
INSERT IGNORE INTO district (code, region_code, name) VALUES ('0314', '03', '북구');
INSERT IGNORE INTO district (code, region_code, name) VALUES ('0315', '03', '서구');
INSERT IGNORE INTO district (code, region_code, name) VALUES ('0316', '03', '수성구');
INSERT IGNORE INTO district (code, region_code, name) VALUES ('0317', '03', '중구');
INSERT IGNORE INTO district (code, region_code, name) VALUES ('0411', '04', '강화군');
INSERT IGNORE INTO district (code, region_code, name) VALUES ('0412', '04', '계양구');
INSERT IGNORE INTO district (code, region_code, name) VALUES ('0413', '04', '남동구');
INSERT IGNORE INTO district (code, region_code, name) VALUES ('0414', '04', '동구');
INSERT IGNORE INTO district (code, region_code, name) VALUES ('0415', '04', '미추홀구');
INSERT IGNORE INTO district (code, region_code, name) VALUES ('0416', '04', '부평구');
INSERT IGNORE INTO district (code, region_code, name) VALUES ('0417', '04', '서구');
INSERT IGNORE INTO district (code, region_code, name) VALUES ('0418', '04', '연수구');
INSERT IGNORE INTO district (code, region_code, name) VALUES ('0419', '04', '옹진군');
INSERT IGNORE INTO district (code, region_code, name) VALUES ('0420', '04', '중구');
INSERT IGNORE INTO district (code, region_code, name) VALUES ('0506', '05', '광산구');
INSERT IGNORE INTO district (code, region_code, name) VALUES ('0507', '05', '남구');
INSERT IGNORE INTO district (code, region_code, name) VALUES ('0508', '05', '동구');
INSERT IGNORE INTO district (code, region_code, name) VALUES ('0509', '05', '북구');
INSERT IGNORE INTO district (code, region_code, name) VALUES ('0510', '05', '서구');
INSERT IGNORE INTO district (code, region_code, name) VALUES ('0606', '06', '대덕구');
INSERT IGNORE INTO district (code, region_code, name) VALUES ('0607', '06', '동구');
INSERT IGNORE INTO district (code, region_code, name) VALUES ('0608', '06', '서구');
INSERT IGNORE INTO district (code, region_code, name) VALUES ('0609', '06', '유성구');
INSERT IGNORE INTO district (code, region_code, name) VALUES ('0610', '06', '중구');
INSERT IGNORE INTO district (code, region_code, name) VALUES ('0706', '07', '남구');
INSERT IGNORE INTO district (code, region_code, name) VALUES ('0707', '07', '동구');
INSERT IGNORE INTO district (code, region_code, name) VALUES ('0708', '07', '북구');
INSERT IGNORE INTO district (code, region_code, name) VALUES ('0709', '07', '울주군');
INSERT IGNORE INTO district (code, region_code, name) VALUES ('0710', '07', '중구');
INSERT IGNORE INTO district (code, region_code, name) VALUES ('0802', '08', '세종특별자치시');
INSERT IGNORE INTO district (code, region_code, name) VALUES ('0943', '09', '가평군');
INSERT IGNORE INTO district (code, region_code, name) VALUES ('0944', '09', '고양시 덕양구');
INSERT IGNORE INTO district (code, region_code, name) VALUES ('0945', '09', '고양시 일산동구');
INSERT IGNORE INTO district (code, region_code, name) VALUES ('0946', '09', '고양시 일산서구');
INSERT IGNORE INTO district (code, region_code, name) VALUES ('0947', '09', '과천시');
INSERT IGNORE INTO district (code, region_code, name) VALUES ('0948', '09', '광명시');
INSERT IGNORE INTO district (code, region_code, name) VALUES ('0949', '09', '광주시');
INSERT IGNORE INTO district (code, region_code, name) VALUES ('0950', '09', '구리시');
INSERT IGNORE INTO district (code, region_code, name) VALUES ('0951', '09', '군포시');
INSERT IGNORE INTO district (code, region_code, name) VALUES ('0952', '09', '김포시');
INSERT IGNORE INTO district (code, region_code, name) VALUES ('0953', '09', '남양주시');
INSERT IGNORE INTO district (code, region_code, name) VALUES ('0954', '09', '동두천시');
INSERT IGNORE INTO district (code, region_code, name) VALUES ('0955', '09', '부천시');
INSERT IGNORE INTO district (code, region_code, name) VALUES ('0956', '09', '성남시 분당구');
INSERT IGNORE INTO district (code, region_code, name) VALUES ('0957', '09', '성남시 수정구');
INSERT IGNORE INTO district (code, region_code, name) VALUES ('0958', '09', '성남시 중원구');
INSERT IGNORE INTO district (code, region_code, name) VALUES ('0959', '09', '수원시 권선구');
INSERT IGNORE INTO district (code, region_code, name) VALUES ('0960', '09', '수원시 영통구');
INSERT IGNORE INTO district (code, region_code, name) VALUES ('0961', '09', '수원시 장안구');
INSERT IGNORE INTO district (code, region_code, name) VALUES ('0962', '09', '수원시 팔달구');
INSERT IGNORE INTO district (code, region_code, name) VALUES ('0963', '09', '시흥시');
INSERT IGNORE INTO district (code, region_code, name) VALUES ('0964', '09', '안산시 단원구');
INSERT IGNORE INTO district (code, region_code, name) VALUES ('0965', '09', '안산시 상록구');
INSERT IGNORE INTO district (code, region_code, name) VALUES ('0966', '09', '안성시');
INSERT IGNORE INTO district (code, region_code, name) VALUES ('0967', '09', '안양시 동안구');
INSERT IGNORE INTO district (code, region_code, name) VALUES ('0968', '09', '안양시 만안구');
INSERT IGNORE INTO district (code, region_code, name) VALUES ('0969', '09', '양주시');
INSERT IGNORE INTO district (code, region_code, name) VALUES ('0970', '09', '양평군');
INSERT IGNORE INTO district (code, region_code, name) VALUES ('0971', '09', '여주시');
INSERT IGNORE INTO district (code, region_code, name) VALUES ('0972', '09', '연천군');
INSERT IGNORE INTO district (code, region_code, name) VALUES ('0973', '09', '오산시');
INSERT IGNORE INTO district (code, region_code, name) VALUES ('0974', '09', '용인시 기흥구');
INSERT IGNORE INTO district (code, region_code, name) VALUES ('0975', '09', '용인시 수지구');
INSERT IGNORE INTO district (code, region_code, name) VALUES ('0976', '09', '용인시 처인구');
INSERT IGNORE INTO district (code, region_code, name) VALUES ('0977', '09', '의왕시');
INSERT IGNORE INTO district (code, region_code, name) VALUES ('0978', '09', '의정부시');
INSERT IGNORE INTO district (code, region_code, name) VALUES ('0979', '09', '이천시');
INSERT IGNORE INTO district (code, region_code, name) VALUES ('0980', '09', '파주시');
INSERT IGNORE INTO district (code, region_code, name) VALUES ('0981', '09', '평택시');
INSERT IGNORE INTO district (code, region_code, name) VALUES ('0982', '09', '포천시');
INSERT IGNORE INTO district (code, region_code, name) VALUES ('0983', '09', '하남시');
INSERT IGNORE INTO district (code, region_code, name) VALUES ('0984', '09', '화성시');
INSERT IGNORE INTO district (code, region_code, name) VALUES ('1116', '11', '괴산군');
INSERT IGNORE INTO district (code, region_code, name) VALUES ('1117', '11', '단양군');
INSERT IGNORE INTO district (code, region_code, name) VALUES ('1118', '11', '보은군');
INSERT IGNORE INTO district (code, region_code, name) VALUES ('1119', '11', '영동군');
INSERT IGNORE INTO district (code, region_code, name) VALUES ('1120', '11', '옥천군');
INSERT IGNORE INTO district (code, region_code, name) VALUES ('1121', '11', '음성군');
INSERT IGNORE INTO district (code, region_code, name) VALUES ('1122', '11', '제천시');
INSERT IGNORE INTO district (code, region_code, name) VALUES ('1123', '11', '증평군');
INSERT IGNORE INTO district (code, region_code, name) VALUES ('1124', '11', '진천군');
INSERT IGNORE INTO district (code, region_code, name) VALUES ('1125', '11', '청원군');
INSERT IGNORE INTO district (code, region_code, name) VALUES ('1126', '11', '청주시 상당구');
INSERT IGNORE INTO district (code, region_code, name) VALUES ('1127', '11', '청주시 서원구');
INSERT IGNORE INTO district (code, region_code, name) VALUES ('1128', '11', '청주시 청원구');
INSERT IGNORE INTO district (code, region_code, name) VALUES ('1129', '11', '청주시 흥덕구');
INSERT IGNORE INTO district (code, region_code, name) VALUES ('1130', '11', '충주시');
INSERT IGNORE INTO district (code, region_code, name) VALUES ('1217', '12', '계룡시');
INSERT IGNORE INTO district (code, region_code, name) VALUES ('1218', '12', '공주시');
INSERT IGNORE INTO district (code, region_code, name) VALUES ('1219', '12', '금산군');
INSERT IGNORE INTO district (code, region_code, name) VALUES ('1220', '12', '논산시');
INSERT IGNORE INTO district (code, region_code, name) VALUES ('1221', '12', '당진시');
INSERT IGNORE INTO district (code, region_code, name) VALUES ('1222', '12', '보령시');
INSERT IGNORE INTO district (code, region_code, name) VALUES ('1223', '12', '부여군');
INSERT IGNORE INTO district (code, region_code, name) VALUES ('1224', '12', '서산시');
INSERT IGNORE INTO district (code, region_code, name) VALUES ('1225', '12', '서천군');
INSERT IGNORE INTO district (code, region_code, name) VALUES ('1226', '12', '아산시');
INSERT IGNORE INTO district (code, region_code, name) VALUES ('1227', '12', '예산군');
INSERT IGNORE INTO district (code, region_code, name) VALUES ('1228', '12', '천안시 동남구');
INSERT IGNORE INTO district (code, region_code, name) VALUES ('1229', '12', '천안시 서북구');
INSERT IGNORE INTO district (code, region_code, name) VALUES ('1230', '12', '청양군');
INSERT IGNORE INTO district (code, region_code, name) VALUES ('1231', '12', '태안군');
INSERT IGNORE INTO district (code, region_code, name) VALUES ('1232', '12', '홍성군');
INSERT IGNORE INTO district (code, region_code, name) VALUES ('1316', '13', '고창군');
INSERT IGNORE INTO district (code, region_code, name) VALUES ('1317', '13', '군산시');
INSERT IGNORE INTO district (code, region_code, name) VALUES ('1318', '13', '김제시');
INSERT IGNORE INTO district (code, region_code, name) VALUES ('1319', '13', '남원시');
INSERT IGNORE INTO district (code, region_code, name) VALUES ('1320', '13', '무주군');
INSERT IGNORE INTO district (code, region_code, name) VALUES ('1321', '13', '부안군');
INSERT IGNORE INTO district (code, region_code, name) VALUES ('1322', '13', '순창군');
INSERT IGNORE INTO district (code, region_code, name) VALUES ('1323', '13', '완주군');
INSERT IGNORE INTO district (code, region_code, name) VALUES ('1324', '13', '익산시');
INSERT IGNORE INTO district (code, region_code, name) VALUES ('1325', '13', '임실군');
INSERT IGNORE INTO district (code, region_code, name) VALUES ('1326', '13', '장수군');
INSERT IGNORE INTO district (code, region_code, name) VALUES ('1327', '13', '전주시 덕진구');
INSERT IGNORE INTO district (code, region_code, name) VALUES ('1328', '13', '전주시 완산구');
INSERT IGNORE INTO district (code, region_code, name) VALUES ('1329', '13', '정읍시');
INSERT IGNORE INTO district (code, region_code, name) VALUES ('1330', '13', '진안군');
INSERT IGNORE INTO district (code, region_code, name) VALUES ('1423', '14', '강진군');
INSERT IGNORE INTO district (code, region_code, name) VALUES ('1424', '14', '고흥군');
INSERT IGNORE INTO district (code, region_code, name) VALUES ('1425', '14', '곡성군');
INSERT IGNORE INTO district (code, region_code, name) VALUES ('1426', '14', '광양시');
INSERT IGNORE INTO district (code, region_code, name) VALUES ('1427', '14', '구례군');
INSERT IGNORE INTO district (code, region_code, name) VALUES ('1428', '14', '나주시');
INSERT IGNORE INTO district (code, region_code, name) VALUES ('1429', '14', '담양군');
INSERT IGNORE INTO district (code, region_code, name) VALUES ('1430', '14', '목포시');
INSERT IGNORE INTO district (code, region_code, name) VALUES ('1431', '14', '무안군');
INSERT IGNORE INTO district (code, region_code, name) VALUES ('1432', '14', '보성군');
INSERT IGNORE INTO district (code, region_code, name) VALUES ('1433', '14', '순천시');
INSERT IGNORE INTO district (code, region_code, name) VALUES ('1434', '14', '신안군');
INSERT IGNORE INTO district (code, region_code, name) VALUES ('1435', '14', '여수시');
INSERT IGNORE INTO district (code, region_code, name) VALUES ('1436', '14', '영광군');
INSERT IGNORE INTO district (code, region_code, name) VALUES ('1437', '14', '영암군');
INSERT IGNORE INTO district (code, region_code, name) VALUES ('1438', '14', '완도군');
INSERT IGNORE INTO district (code, region_code, name) VALUES ('1439', '14', '장성군');
INSERT IGNORE INTO district (code, region_code, name) VALUES ('1440', '14', '장흥군');
INSERT IGNORE INTO district (code, region_code, name) VALUES ('1441', '14', '진도군');
INSERT IGNORE INTO district (code, region_code, name) VALUES ('1442', '14', '함평군');
INSERT IGNORE INTO district (code, region_code, name) VALUES ('1443', '14', '해남군');
INSERT IGNORE INTO district (code, region_code, name) VALUES ('1444', '14', '화순군');
INSERT IGNORE INTO district (code, region_code, name) VALUES ('1525', '15', '경산시');
INSERT IGNORE INTO district (code, region_code, name) VALUES ('1526', '15', '경주시');
INSERT IGNORE INTO district (code, region_code, name) VALUES ('1527', '15', '고령군');
INSERT IGNORE INTO district (code, region_code, name) VALUES ('1528', '15', '구미시');
INSERT IGNORE INTO district (code, region_code, name) VALUES ('1529', '15', '군위군');
INSERT IGNORE INTO district (code, region_code, name) VALUES ('1530', '15', '김천시');
INSERT IGNORE INTO district (code, region_code, name) VALUES ('1531', '15', '문경시');
INSERT IGNORE INTO district (code, region_code, name) VALUES ('1532', '15', '봉화군');
INSERT IGNORE INTO district (code, region_code, name) VALUES ('1533', '15', '상주시');
INSERT IGNORE INTO district (code, region_code, name) VALUES ('1534', '15', '성주군');
INSERT IGNORE INTO district (code, region_code, name) VALUES ('1535', '15', '안동시');
INSERT IGNORE INTO district (code, region_code, name) VALUES ('1536', '15', '영덕군');
INSERT IGNORE INTO district (code, region_code, name) VALUES ('1537', '15', '영양군');
INSERT IGNORE INTO district (code, region_code, name) VALUES ('1538', '15', '영주시');
INSERT IGNORE INTO district (code, region_code, name) VALUES ('1539', '15', '영천시');
INSERT IGNORE INTO district (code, region_code, name) VALUES ('1540', '15', '예천군');
INSERT IGNORE INTO district (code, region_code, name) VALUES ('1541', '15', '울릉군');
INSERT IGNORE INTO district (code, region_code, name) VALUES ('1542', '15', '울진군');
INSERT IGNORE INTO district (code, region_code, name) VALUES ('1543', '15', '의성군');
INSERT IGNORE INTO district (code, region_code, name) VALUES ('1544', '15', '청도군');
INSERT IGNORE INTO district (code, region_code, name) VALUES ('1545', '15', '청송군');
INSERT IGNORE INTO district (code, region_code, name) VALUES ('1546', '15', '칠곡군');
INSERT IGNORE INTO district (code, region_code, name) VALUES ('1547', '15', '포항시 남구');
INSERT IGNORE INTO district (code, region_code, name) VALUES ('1548', '15', '포항시 북구');
INSERT IGNORE INTO district (code, region_code, name) VALUES ('1623', '16', '거제시');
INSERT IGNORE INTO district (code, region_code, name) VALUES ('1624', '16', '거창군');
INSERT IGNORE INTO district (code, region_code, name) VALUES ('1625', '16', '고성군');
INSERT IGNORE INTO district (code, region_code, name) VALUES ('1626', '16', '김해시');
INSERT IGNORE INTO district (code, region_code, name) VALUES ('1627', '16', '남해군');
INSERT IGNORE INTO district (code, region_code, name) VALUES ('1628', '16', '밀양시');
INSERT IGNORE INTO district (code, region_code, name) VALUES ('1629', '16', '사천시');
INSERT IGNORE INTO district (code, region_code, name) VALUES ('1630', '16', '산청군');
INSERT IGNORE INTO district (code, region_code, name) VALUES ('1631', '16', '양산시');
INSERT IGNORE INTO district (code, region_code, name) VALUES ('1632', '16', '의령군');
INSERT IGNORE INTO district (code, region_code, name) VALUES ('1633', '16', '진주시');
INSERT IGNORE INTO district (code, region_code, name) VALUES ('1634', '16', '창녕군');
INSERT IGNORE INTO district (code, region_code, name) VALUES ('1635', '16', '창원시 마산합포구');
INSERT IGNORE INTO district (code, region_code, name) VALUES ('1636', '16', '창원시 마산회원구');
INSERT IGNORE INTO district (code, region_code, name) VALUES ('1637', '16', '창원시 성산구');
INSERT IGNORE INTO district (code, region_code, name) VALUES ('1638', '16', '창원시 의창구');
INSERT IGNORE INTO district (code, region_code, name) VALUES ('1639', '16', '창원시 진해구');
INSERT IGNORE INTO district (code, region_code, name) VALUES ('1640', '16', '통영시');
INSERT IGNORE INTO district (code, region_code, name) VALUES ('1641', '16', '하동군');
INSERT IGNORE INTO district (code, region_code, name) VALUES ('1642', '16', '함안군');
INSERT IGNORE INTO district (code, region_code, name) VALUES ('1643', '16', '함양군');
INSERT IGNORE INTO district (code, region_code, name) VALUES ('1644', '16', '합천군');
INSERT IGNORE INTO district (code, region_code, name) VALUES ('1703', '17', '서귀포시');
INSERT IGNORE INTO district (code, region_code, name) VALUES ('1704', '17', '제주시');
INSERT IGNORE INTO district (code, region_code, name) VALUES ('1019', '10', '강릉시');
INSERT IGNORE INTO district (code, region_code, name) VALUES ('1020', '10', '고성군');
INSERT IGNORE INTO district (code, region_code, name) VALUES ('1021', '10', '동해시');
INSERT IGNORE INTO district (code, region_code, name) VALUES ('1022', '10', '삼척시');
INSERT IGNORE INTO district (code, region_code, name) VALUES ('1023', '10', '속초시');
INSERT IGNORE INTO district (code, region_code, name) VALUES ('1024', '10', '양구군');
INSERT IGNORE INTO district (code, region_code, name) VALUES ('1025', '10', '양양군');
INSERT IGNORE INTO district (code, region_code, name) VALUES ('1026', '10', '영월군');
INSERT IGNORE INTO district (code, region_code, name) VALUES ('1027', '10', '원주시');
INSERT IGNORE INTO district (code, region_code, name) VALUES ('1028', '10', '인제군');
INSERT IGNORE INTO district (code, region_code, name) VALUES ('1029', '10', '정선군');
INSERT IGNORE INTO district (code, region_code, name) VALUES ('1030', '10', '철원군');
INSERT IGNORE INTO district (code, region_code, name) VALUES ('1031', '10', '춘천시');
INSERT IGNORE INTO district (code, region_code, name) VALUES ('1032', '10', '태백시');
INSERT IGNORE INTO district (code, region_code, name) VALUES ('1033', '10', '평창군');
INSERT IGNORE INTO district (code, region_code, name) VALUES ('1034', '10', '홍천군');
INSERT IGNORE INTO district (code, region_code, name) VALUES ('1035', '10', '화천군');
INSERT IGNORE INTO district (code, region_code, name) VALUES ('1036', '10', '횡성군');
INSERT IGNORE INTO district (code, region_code, name) VALUES ('0985', '09', '부천시 소사구');
INSERT IGNORE INTO district (code, region_code, name) VALUES ('0986', '09', '부천시 오정구');
INSERT IGNORE INTO district (code, region_code, name) VALUES ('0987', '09', '부천시 원미구');
INSERT IGNORE INTO district (code, region_code, name) VALUES ('1645', '16', '진해시');
INSERT IGNORE INTO district (code, region_code, name) VALUES ('0988', '09', '화성시 동탄구');
INSERT IGNORE INTO district (code, region_code, name) VALUES ('0989', '09', '화성시 만세구');
INSERT IGNORE INTO district (code, region_code, name) VALUES ('0990', '09', '화성시 병점구');
INSERT IGNORE INTO district (code, region_code, name) VALUES ('0991', '09', '화성시 효행구');
